version: '3'
services:
  php:
    build:
      context: ./containers
      dockerfile: php/Dockerfile
    container_name: laravel-php
    restart: always
    volumes:
      - ./laravel:/var/www/html
      - ./containers/php:/usr/local/etc/php/custom.d
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
    depends_on:
      - mysql


  nginx:
    image: nginx:1.17
    container_name: laravel-nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./laravel:/var/www/html
      - ./containers/nginx/config:/etc/nginx/conf.d
      - ./containers/nginx/ssl:/etc/nginx/ssl
      - ./containers/certbot/conf:/etc/letsencrypt
      - ./containers/certbot/www:/var/www/certbot
    depends_on:
      - php
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./containers/certbot/conf:/etc/letsencrypt
      - ./containers/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: laravel-mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: bmC5kgv6SMnRVFU3
      MYSQL_DATABASE: partnerhub
      MYSQL_PASSWORD: zK94JAAJC9NyJPJn
      MYSQL_USER: laravel
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
    depends_on:
      - nginx

  cron:
    build:
      context: ./containers/php-cron
      dockerfile: Dockerfile
    container_name: php-cron
    restart: always
    volumes:
      - ./laravel:/var/www/html
      - ./cronlog/cron.log:/var/log/cron.log
    depends_on:
      - nginx

  php-worker:
    build:
      context: ./containers/php-worker
      dockerfile: Dockerfile
    container_name: php-worker
    volumes:
      - ./laravel:/var/www/html
    depends_on:
      - nginx
